FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/

# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir --timeout=300 -r requirements.txt


COPY . /app/

CMD ["python", "client2.py"]
