apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-server
  namespace: default 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower-server
  template:
    metadata:
      labels:
        app: flower-server
    spec:
      containers:
      - name: flower-server
        image: sagnik3788/flower-server:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "500Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
